nome = input('Digite seu nome completo : ')
print(nome.upper())
print(nome.lower())
print('Seu nome tem {} letras'.format(len(nome)-(nome.count(' '))))
dividido = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(dividido[0],len(dividido[0])))