frase = input('Digite uma frase : ').lower().strip()
print(frase)
print('Quantas letras A na frase : {}'.format(frase.count('a')))
print('Ela aparece primeiro na posição {}'.format(frase.find('a')+1))
print('Ela aparece por último na posição {}'.format(frase.rfind('a')+1))